name: my_first_workflow
# This workflow is intended to help ensure that PRs modifying indgoag.ads have a PR Title that will later be converted to a
# required conventional-commit-formatted squashed commit message for use in circleci workflows that publish the package to codeartifact
on: workflow_dispatch

jobs:
  DummyJob:
    runs-on: ubuntu-latest
    steps:
      - name: DummyStep
        run: echo "Dummy Step Ran"
