name: SDK Module Preconditions
# This workflow is intended to help ensure that PRs modifying indgoag.ads have a PR Title that will later be converted to a
# required conventional-commit-formatted squashed commit message for use in circleci workflows that publish the package to codeartifact
on: 
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - main
    paths:
      - 'indigoag/ads/**'


jobs:
  check_pr_title_for_conventional_commit_format:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: ls
      - uses: actions/checkout@v2
        name: Checkout
      - run: pwd
      - run: ls
      - uses: ./
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

